version: '3.8'

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: maor
      MONGO_INITDB_DATABASE: mydb
    networks:
      my_network:
        ipv4_address: 172.16.0.2
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # Exposes MongoDB's default port and mounts a volume for data persistence

  react:
    build: ./test1
    image: maoravidan/projectapp:react100
    networks:
      my_network:
        ipv4_address: 172.16.0.3
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    # Builds the React application from the local directory and exposes port 3000
    # The React app will wait for the FastAPI service to be ready

  fastapi:
    build: ./fast_api
    image: maoravidan/projectapp:fastapi13
    networks:
      my_network:
        ipv4_address: 172.16.0.4
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    # Builds the FastAPI application from the local directory and exposes port 8000
    # The FastAPI service will wait for the MongoDB service to be ready

volumes:
  mongodb_data:
    # Defines a volume for MongoDB data
